name: Build and publish package to TestPyPI

on:
  push:
    branches:
      - release-candidate

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout to release-candidate
        uses: actions/checkout@v4.1.1
        with:
          ref: release-candidate
      - name: Set up Python 3.12
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12'
      - name: Install in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .[build]
      - name: Build
        run: package --build-number
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          repository-url: https://test.pypi.org/legacy/
